server:
  port: 8088
  servlet:
    context-path: /api/v1

spring:
  config:
    import:
      - classpath:application-db.yml
      - classpath:application-ai.yml
      - classpath:application-auth.yml
      - classpath:application-storage.yml
  threads:
    virtual:
      enabled: true
  application:
    name: fast-knowledge-server
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  global-config:
    db-config:
      id-type: auto

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}
